swagger: '2.0'
info:
  description: Definition of the SBTech Casino API.
  version: 0.2.0
  title: SBTech Casino OpenAPI
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: eram@sbtech.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: casino.sbtech.swagger.io
basePath: /v2
tags:
  - name: CasAPI
    description: Client API for getting a game-set and launching a game
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:

  /games:
    get:
      tags:
        - CasAPI
      summary: Get a gameshift game-set
      operationId: getGames
      produces:
        - application/json
      parameters:
        - name: lang
          in: query
          description: 2 chars language code using ISO 639-1
          required: false
          type: string
          default: en
        - name: gameshift
          in: query
          description: Gameshift name
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/IGameSet'
        '400':
          description: Invalid request data
          schema:
            type: string
        '401':
          description: Invalid token
          schema:
            type: string
        '403':
          description: Operation prohibited
          schema:
            type: string
        '404':
          description: Resource doesn't exist
          schema:
            type: string
        '500':
          description: Server error
          schema:
            type: string
        'default': 
          description: Unexpected error      
          schema:
            type: string
      security:
        - Bearer: []

  /games/info:
    get:
      tags:
        - CasAPI
      summary: Receive games' extended information
      operationId: getGameExt
      produces:
        - application/json
      parameters:
        - name: lang
          in: query
          description: 2 chars language code using ISO 639-1
          required: false
          type: string
          default: en
        - name: ids
          in: query
          description: Array of game ids
          required: true
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/IGameExtra'
        '400':
          description: Invalid request data
          schema:
            type: string
        '401':
          description: Invalid token
          schema:
            type: string
        '403':
          description: Operation prohibited
          schema:
            type: string
        '404':
          description: Resource doesn't exist
          schema:
            type: string
        '500':
          description: Server error
          schema:
            type: string
        'default': 
          description: Unexpected error      
          schema:
            type: string
      security:
        - Bearer: []

  /games/launch:
    get:
      tags:
        - CasAPI
      summary: Get launch-game params. This function should be called right after the player has requested to run a game. The resturned parameters include the url of the game, with all the parameters required to launch it. 
      operationId: launchGameParams
      produces:
        - application/json
      parameters:
        - name: lang
          in: query
          description: 2 chars language code using ISO 639-1
          required: false
          type: string
          default: en
        - name: id
          in: query
          description: Id of game
          required: true
          type: string
        - name: gameshift
          in: query
          description: Gameshift name
          required: true
          type: string
        - name: demo
          in: query
          description: Is demo mode
          required: false
          type: boolean
        - name: channel
          in: query
          description: Launch platform- desktop, mobile or mini-game
          required: true
          type: string
          enum:
          - desktop
          - mobile
          - mini
      responses:
        '200':
          schema:
             $ref: '#/definitions/ILaunchParams'
          description: Successful operation
        '400':
          description: Invalid request data
          schema:
            type: string
        '401':
          description: Invalid token
          schema:
            type: string
        '403':
          description: Operation prohibited
          schema:
            type: string
        '404':
          description: Resource doesn't exist
          schema:
            type: string
        '500':
          description: Server error
          schema:
            type: string
        'default': 
          description: Unexpected error      
          schema:
            type: string
      security:
        - Bearer: []


  /ping:
    get:
      tags:
        - CasAPI
      summary: Server heartbeat operation
      operationId: ping
      # description: This operation shows how to override the global security defined above, as we want to open it up for all users.
      # We want to require no security schemes and override the globally define security scheme.
      # To do that, we simply provide an empty array to the 'security' property.
      security: [ ]
      responses:
        '200':
          description: OK
        'default': 
          description: Unexpected error      
          schema:
            type: string

definitions:

  IMedia:
    type: object
    required:
      - path
    properties:
      path:
        type: string
        description: location in CDN
      width:
        type: integer
        description: width in px
      height:
        type: integer
        description: height in px
  
  IGameExtra:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      description:
        type: string
      screenshots:
        type: array
        items:
          $ref: '#/definitions/IMedia'
      minBet:
        type: number
      maxBet:
        type: number
      currency:
        type: string
        description: currency display symbol        
      features:
        type: object
        description: a key-value map
        required:
          - default
        properties:
          default:
            type: string
        additionalProperties:
          type: string

 
  IGame:
    type: object
    required:
      - id
      - name
      - props
    properties:
      id:
        type: string
      name:
        type: string
        description: display name
      type:
        type: string
        description: game type name
      tags:
        type: array
        items:
          type: string
          description: tag-code | category-id
      thumbnails:
        type: array
        items:
          $ref: '#/definitions/IMedia'
      background:
        $ref: '#/definitions/IMedia'
      studio:
        type: string
        description: game studio name
      popularity:
        type: integer
        format: integer
      priority:
        type: integer
        format: integer
      launchDate:
        type: string
        format: date
        description: ISO standard date- 1985-04-12
      lastPlayed:
        type: string
        format: dateTime
        description: last played date-time - RFC3339
      gameFlag:
        description: game icon promotional overlay.
        type: string
        enum:
          - new
          - hot
          - promoted
      props:
        type: object
        properties:
          hasDemo:
            type: boolean
          isMini:
            type: boolean
          isMobile:
            type: boolean
          isDesktop:
            type: boolean
      jackpotId: 
        type: string

  IGameSet:
    type: object
    required:
      - gameSetId
      - gameShiftId
      - games
    properties:
      gameSetId:
        type: string
        description: Unique ID of the returned game-set 
      gameShiftId:
        type: string
        description: Unique ID of the returned game-shift 
      cdn:
        type: string
        description: Root path for resources.
      games:
        type: array
        items:
          $ref: '#/definitions/IGame'

  ILaunchParams:
    type: object
    required:
      - gameId
      - provider
      - params
    properties:
      gameId:
        type: string
      provider:
        type: string
      params:
        type: object
